# Generated by Django 4.1.13 on 2024-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_netbankingpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='NetBankingPayment',
        ),
    ]
