# Generated by Django 4.1.13 on 2024-02-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_netb_delete_netbankingpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Netb',
        ),
    ]
