# Generated by Django 4.1.13 on 2024-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
