# Generated by Django 4.1.13 on 2024-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='upi',
            name='name',
            field=models.IntegerField(),
        ),
    ]
