# Generated by Django 4.1.13 on 2024-02-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_upi_amount_alter_upi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upi',
            old_name='name',
            new_name='userID',
        ),
    ]
