# Generated by Django 4.1.13 on 2024-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_name_upi_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upi',
            name='userID',
        ),
        migrations.AddField(
            model_name='upi',
            name='name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upi',
            name='amount',
            field=models.CharField(max_length=30),
        ),
    ]
