# Generated by Django 4.1.13 on 2024-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
