# Generated by Django 4.1.13 on 2024-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('expiration', models.DateField()),
                ('cvv', models.CharField(max_length=15)),
            ],
        ),
    ]
