# Generated by Django 5.0.2 on 2024-02-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_sellerform_delete_sform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerForm',
        ),
    ]
