# Generated by Django 5.0.2 on 2024-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
